### ISSUE TITLE
getConsoleCursorInfo exception w/ hideCursor on Windows

### ISSUE THREAD

**Issue by creswick** [batterseapower/ansi-terminal#1]
This bug seems to only occur in some relatively specific circumstances -- we've been able to reproduce it reliably by ssh-ing into a cygwin shell running on windows:

Reproduction:
- ssh into a cygwin ssh server running on windows (32-bit XP, 32-bit Vista and 64-bit Vista all exhibit this problem, we haven't tested others.)
- start up ghci (`ghcii.sh` -- 6.10.4 and 6.12.1 both exhibit the bug, haven't tested others.)
- load the `System.Console.ANSI` module:  (`:m + System.Console.ANSI`)
- invoke `hideCursor`.  This should result in: `*** Exception: getConsoleCursorInfo: invalid argument (The handle is invalid.)`

This happens as either an unprivileged user or as administrator, so we do not believe it is related to the cygwin bug [discussed here](http://bit.ly/9WO7uf), although the reproduction is similar. (This bug also pre-dated cygwin 1.7.)  This bug does _not_ happen when logged in directly to a windows system, although you _can_ ssh to localhost to reproduce it.

This came up because it prevents test-framework from running on windows build slaves that are activated via ssh-ing into a cygwin server.  (even using --plain to reduce the test-framework output is insufficient, since the cursor is still hidden.)  I think hideCursor (and other functions that may trigger this bug) should return error values instead of throwing exceptions. 

Here's a complete log of a ghci session that triggers the bug:

```
hudson@corona ~
$ ghcii.sh 
GHCi, version 6.12.1: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package ffi-1.0 ... linking ... done.
Prelude> :m + System.Console.ANSI
Prelude System.Console.ANSI> hideCursor
Loading package bytestring-0.9.1.5 ... linking ... done.
Loading package Win32-2.2.0.1 ... linking ... done.
Loading package ansi-terminal-0.5.2 ... linking ... done.
*** Exception: getConsoleCursorInfo: invalid argument (The handle is invalid.)
Prelude System.Console.ANSI> 
```

**Comment by batterseapower** [comment]
Thanks for the report Rogan!

You can actually reproduce this much more simply: just try using ansi-terminal under a non-standard Windows terminal such as mintty or Terminator. (BTW I highly recommend mintty if you are using Cygwin - you can install it through setup.exe).

What I've decided to do is to fall back on outputting the ANSI escape codes when stdout/stderr do not map to a real handle to a console. This is not always the right thing to do, but will be correct in 99% of cases. In particular, since Terminator and mintty implement the ANSI standard, this means that ansi-terminal now does the right thing when run under them. I suspect that your ssh session will work correctly as well.

I've uploaded the new version to Hackage as v0.5.3: http://hackage.haskell.org/package/ansi-terminal-0.5.3

Let me know if you have any trouble with the new behaviour.

**Comment by creswick** [comment]
Thanks Max,  this looks good!

**Comment by kowey** [comment]
Hi Max, we're trying to use test-framework 0.3.2 (and we think built against ansi-terminal-0.5.3) against a Windows build slave, and we're getting "getConsoleCursorInfo: invalid argument" errors.  Could it be related to this bug?  Thanks!

The output we get is http://buildbot.darcs.net/builders/6.10.3%20Vista/builds/49/steps/test/logs/stdio

**Comment by batterseapower** [comment]
Thanks for the report. This should be fixed in 0.3.3

**Comment by mornfall** [comment]
I have ansi-terminal 0.5.4 and test-framework 0.3.3 and the problem still persists. The tests run in cmd.exe but not in rxvt nor in buildbot.

**Comment by mornfall** [comment]
I take that back. With --plain, I don't get the exception anymore. In buildbot, the runner simply hangs with --plain, with no output. I will try that in rxvt (another test runner works in rxvt on the same machine).

**Comment by batterseapower** [comment]
I've tried running the test-framework-example program whose source code is at http://github.com/batterseapower/test-framework/tree/master/example/, and it runs perfectly in rxvt and mintty on Windows for me (after my last set of changes).

I'm confused as to why it doesn't work for you. Can you give me steps to reproduce?

**Comment by mornfall** [comment]
Ok, I have tracked this down to be (somewhat) unrelated to test-framework. I was trying to removeFile a file that was open, which for some reason (when running in win32 + test-framework) just hung the process indefinitely. (This would normally just die with an error message, so there may be some test-framework interaction. Not ansi-terminal related though. I'll look again and maybe file it under test-framework when I have more time.)
